独断専行を反省する気持ち
udon-sysken/udon-sysken.github.io pull request #1
Opened 2019-01-02 15:21 UTC by Umbroom

2019-01-02 15:42 UTC, namachan10777 commented
オー結構好きです。画面幅変えても対応してきて流石。
# HTMLの意味的な改善点
 - [ ] sectionにはheaderを入れる
 - [ ] copyrightはfooterでhtmlの直下に入れる
# デザイン
[こういう](https://tinykitten.me)スクロールしていくと情報が表示されるタイプのもあります。
デザイン何も分からないので勘で言っていますが、画面全体にまんべんなく情報が無くても良いとは思います。我々母語がltrの人間は左から右、上から下と目線が動くのでperformanceが見づらくなっていますね。

画像無いと雰囲気わからない is あるので画像入れたコミット欲しいです。

一画面に詰め込まなくてもスクロールさせても良さそう。

# 開発
pugやsassで書いてCircleCIでdeployとかどうでしょう。CI周りは僕がやるので興味あったらどうですか。やらなくても僕が勝手にやってPR投げますが

2019-01-02 15:50 UTC, namachan10777 requested changes

2019-01-02 15:50 UTC, namachan10777 commented on style.css
> +    font-family: '游ゴシック Medium';
游ゴシックはWindowsとMacには標準で入っていますがフリーフォントではなくLinux等ではデザインが変わってしまう可能性が高いです。[Google Font](https://googlefonts.github.io/japanese/)などのWebフォントを使うとか、游ゴシックが無い環境でも正しく表示されるよう書体の設定とかをした方が良いです。多分...

2019-01-02 15:50 UTC, namachan10777 commented on index.html
> +            <section class="column" id="perf">
sectionにはheaderを入れておきましょう。<h3\>とかを<header\>で囲むと良いです

2019-01-02 15:50 UTC, Umbroom commented
あれ、僕の手元にある本（HTML5&CSS3標準デザイン講座：草野あけみ）だとh1タグなどでheaderの代用してますが……

開発環境に凝るのは構いませんが，一応部活でも進めることを考えると面倒なのはちょっと……新入生の負担が心配です．

2019-01-02 15:50 UTC, namachan10777 commented
アッデザインに関してはRequest changeではないので他の人の意見もお願いします

2019-01-02 15:51 UTC, namachan10777 commented
> あれ、僕の手元にある本（HTML5&CSS3標準デザイン講座：草野あけみ）だとh1タグなどでheaderの代用してますが……

記憶違いだったかもです申し訳ない

2019-01-02 15:52 UTC, namachan10777 commented
> 開発環境に凝るのは構いませんが，一応部活でも進めることを考えると面倒なのはちょっと……新入生の負担が心配です．

申し訳ない :cry: 
:bowing_man:

2019-01-02 15:52 UTC, Umbroom commented
僕fontほんと分からないのでオススメのフォントあればお願いします（@各位）

2019-01-02 15:52 UTC, Mackyson commented
fontにわからない(ﾄﾞｯ)

2019-01-02 15:56 UTC, namachan10777 commented
[これ](https://googlefonts.github.io/japanese/)使うか無指定で僕はやってます。sans-serifとかとfont-weightとかでどうにか...

2019-01-02 16:00 UTC, Umbroom commented
それあんまり琴線に響かなかったんですよね……　さしあたり<ruby>画像<rt>ラフ</rt></ruby>とフォントまわり直しますね

2019-01-02 16:03 UTC, namachan10777 commented
理解。ラフよろしくお願いします :pray:

2019-01-02 16:05 UTC, Mackyson requested changes
大筋がこのままならcontentsは縦に配置しましょう．
実装方法はわかりません！ｗ

2019-01-02 16:05 UTC, Umbroom commented
あの並べ方でないと3列にしたときに見栄えが悪くなるんですよね……　現行の配置を根本から変えるか，なるほどなハックを募集しています。僕としてはdetailの後ろに地図を載せたいのですが。

2019-01-02 16:07 UTC, Umbroom commented
縦に配置すると1列になりそうな予感がします（縦で折り返すのに失敗した敗北者）そうするともうflexboxである必要がなくなりますが．

2019-01-02 16:07 UTC, Mackyson commented
手段と目的が入れ替わっていますが．

2019-01-02 16:08 UTC, Umbroom commented
誰か「flexboxとか使ったつよつよなページ作ろうぜ」みたいなこと言ってませんでした？

2019-01-02 16:09 UTC, namachan10777 commented
flexboxというか過去のブラウザを全部切り捨てるページ

2019-01-02 16:10 UTC, Umbroom commented
とりあえずもう少し余白を作ればいいということでOKです？

2019-01-02 16:11 UTC, namachan10777 commented
基本そんな感じですね。performanceの位置が悪いなと感じたので。performanceを右下に持ってくるだけでも良いとは思いますが、もしかして画像の配置とかで微妙になるかも

2019-01-02 16:15 UTC, kohmoli commented
ああー、左の赤画像とつながるのでダメだと思ってましたが、よく考えたらあれ仮置きの背景色なので差別化できますね．そうします

2019-03-19 16:12 UTC, namachan10777 commented
ワッ凄い。滅茶苦茶現代的なWebサイトっぽい。
 * ロード画面がちょっと長い
 * 下へのスクロールを誘導するなにか(矢印とか)が欲しい
 * コンテンツとコンテンツの間が広い

# コンテンツとコンテンツの感覚

https://tinykitten.me
https://circleci.com
https://elm-lang.org
https://www.preferred-networks.jp/en/

こんな感じにもう少しコンテンツを詰めたほうが見やすいと思います。
詰めるコンテンツが無い件については、本当に申し訳ない...。

2019-03-19 16:16 UTC, namachan10777 commented
矢印で下方向へのスクロールを誘導するか、ナヴィゲーションを付けるか、ヘッダを画面の半分くらいに抑えて下方向へのコンテンツの広がりをユーザに認識させるかしないと分かりづらいと思います。
ナヴィゲーションや矢印で下方向へのコンテンツを示すのは個人のポートフォリオなどでは見られますが、企業のサイトではあまり見られないので見やすさ重視ならヘッダのサイズを制限したほうが良さそう

2019-03-23 17:04 UTC, umbroom commented
で き た

2019-03-26 17:41 UTC, namachan10777 approved these changes

2019-04-06 18:48 UTC, Mackyson commented
見なくていいからマージして→はい……(approve)

2019-04-07 03:30 UTC, umbroom commented
後生だからapproveして下さいそしてdev→masterにもして

2019-04-07 14:45 UTC, umbroom commented
# 💢

2019-04-08 02:35 UTC, Mackyson approved these changes

2019-04-08 02:51 UTC, merged